server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true   #开启Eureka服务发现
#          lower-case-service-id: true
      routes:
        - id: cargoserve
#          uri: lb://cargoserve
          uri: http://localhost:8080
          predicates:
            - Path=/cargo/**
        - id: userserver
#          uri: lb://userserver
          uri: http://localhost:8888
          predicates:
            - Path=/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/ #eurekaserver地址
  instance:
    prefer-ip-address: true